### ISSUE TITLE
WPML schema

### ISSUE THREAD

**Issue by polevaultweb** [deliciousbrains/mergebot-schemas#10]

**Comment by polevaultweb** [comment]
Request https://secure.helpscout.net/conversation/407290047/17246/?folderId=869335

**Comment by polevaultweb** [comment]
https://secure.helpscout.net/conversation/411772229/17455/

**Comment by gilbitron** [comment]
https://secure.helpscout.net/conversation/461477762/19958
https://secure.helpscout.net/conversation/460838566/19931

**Comment by polevaultweb** [comment]
Table Prefix - options `$wpdb->prefix . 'icl_translators_cached`
