### ISSUE TITLE
Ninja Forms Support?

### ISSUE THREAD

**Issue by clifgriffin** [deliciousbrains/mergebot-schemas#14]
I see there is a WIP version of the Ninja Forms schema.

I also realize how complicated it will be since their 2.x to 3.x upgrade code involves their legacy tables and new tables.

Do you envision this being ready to test anytime soon? We're working on a large project right now that could greatly benefit from tracking during upgrades and form modifications.

**Comment by polevaultweb** [comment]
hi @clifgriffin it's on the list, I hope to get to it very soon. The blocker at the moment is that NF 3 uses a flexible data model which Mergebot is yet to support via schemas, so it's not just a case of building the schema, but making a change to Mergebot to support it.

**Comment by clifgriffin** [comment]
Hey oh!
